apiVersion: v1
kind: Service
metadata:
  name: menuservice
spec:
# Uncomment type: NodePort & nodePort: <port> to expose mongo to internet.
  type: NodePort
  ports:
  - name: "8080"
    nodePort: 30084
    port: 8080
    targetPort: 8080
  selector:
    app: menu